# Numpy 

In [2]:
import numpy as np

data = np.random.randn(2, 3)
data

array([[ 0.34912816,  0.75290143, -0.59311311],
       [-0.46746038, -1.04784882,  0.95658572]])

In [3]:
data.shape

(2, 3)

In [4]:
data.dtype

dtype('float64')

## Creating ndarrays
#### array() - accepts any sequence-like object

In [7]:
data1 = [6, 7.5, 8, 0, 1]

In [9]:
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

### zeros(), ones(), and empty()
#### empty() - returns uninitialized values. sometimes with garbage values. 

In [10]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [15]:
np.empty((2,3,2))

array([[[0.00000000e+000, 1.72723382e-077],
        [2.96439388e-323, 0.00000000e+000],
        [9.76118064e-313, 8.60952352e-072]],

       [[7.78934220e-091, 9.60074698e-071],
        [1.55137760e+184, 1.88793803e+185],
        [3.99910963e+252, 8.34402697e-309]]])

## Data Types for ndarrays

In [17]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr1.dtype

dtype('float64')

In [19]:
arr1 = np.array([1, 2, 3], dtype=np.int32)
arr1.dtype

dtype('int32')

## astype() - convert or cast an array to another dtype (decimal part may be truncated)

In [25]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [26]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [27]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

## Arithmetic with NumPy Arrays

In [30]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [31]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [32]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [33]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [34]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [35]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [36]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])