# Numpy 

In [2]:
import numpy as np

data = np.random.randn(2, 3)
data

array([[ 0.34912816,  0.75290143, -0.59311311],
       [-0.46746038, -1.04784882,  0.95658572]])

In [3]:
data.shape

(2, 3)

In [4]:
data.dtype

dtype('float64')

## Creating ndarrays
#### array() - accepts any sequence-like object

In [7]:
data1 = [6, 7.5, 8, 0, 1]

In [9]:
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

### zeros(), ones(), and empty()
#### empty() - returns uninitialized values. sometimes with garbage values. 

In [10]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [15]:
np.empty((2,3,2))

array([[[0.00000000e+000, 1.72723382e-077],
        [2.96439388e-323, 0.00000000e+000],
        [9.76118064e-313, 8.60952352e-072]],

       [[7.78934220e-091, 9.60074698e-071],
        [1.55137760e+184, 1.88793803e+185],
        [3.99910963e+252, 8.34402697e-309]]])

## Data Types for ndarrays

In [17]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr1.dtype

dtype('float64')

In [18]:
arr1 = np.array([1, 2, 3], dtype=np.int32)
arr1.dtype

dtype('int32')